"use strict";
let csrf='',buildings=[],editing=null;
const fields=[['code','Код'],['name','Название'],['level_1_effect','Эффект 1 уровня'],['level_2_effect','Эффект 2 уровня'],['level_3_effect','Эффект 3 уровня'],['image_path','Адрес картинки (не используется)'],['note','Примечание'],['active','Активна']];
async function request(path,options={}){const response=await fetch(path,{cache:'no-store',...options});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
function render(){const list=document.querySelector('#building-admin-list');list.replaceChildren(...buildings.map(item=>{const card=document.createElement('section'),title=document.createElement('h3'),details=document.createElement('p'),button=document.createElement('button');title.textContent=item.name;details.textContent=`${item.code} · I: ${item.level_1_effect||'—'} · II: ${item.level_2_effect||'—'} · III: ${item.level_3_effect||'—'}${item.active?'':' · отключена'}`;button.textContent='Редактировать';button.addEventListener('click',()=>open(item));card.append(title,details,button);return card;}));}
function open(item={active:true}){editing=item;const form=document.querySelector('#building-editor-form');form.replaceChildren();document.querySelector('#building-editor-title').textContent=item.code?`Редактирование: ${item.name}`:'Новая постройка';for(const [field,title] of fields){const label=document.createElement('label');label.textContent=title;const input=document.createElement(field.includes('effect')||field==='note'?'textarea':'input');input.name=field;if(field==='active'){input.type='checkbox';input.checked=item.active;}else{input.value=item[field]??'';if(field==='code'&&item.code)input.readOnly=true;}label.append(input);form.append(label);}const save=document.createElement('button');save.type='submit';save.className='save';save.textContent='Сохранить';form.append(save);document.querySelector('#building-editor').showModal();}
async function load(){buildings=await request('/api/admin/buildings');render();document.querySelector('#building-admin-status').textContent=`Построек: ${buildings.length}`;}
document.querySelector('#add-building').addEventListener('click',()=>open());document.querySelector('#close-building-editor').addEventListener('click',()=>document.querySelector('#building-editor').close());
document.querySelector('#building-editor-form').addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));data.active=event.currentTarget.elements.active.checked;const code=data.code;if(editing.code)delete data.code;try{await request(editing.code?`/api/admin/buildings/${encodeURIComponent(editing.code)}`:'/api/admin/buildings',{method:editing.code?'PATCH':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});await load();document.querySelector('#building-editor').close();document.querySelector('#building-admin-status').textContent=`Сохранено: ${editing.code||code}`;}catch(error){document.querySelector('#building-admin-status').textContent=error.message;}});
(async()=>{try{const me=await request('/api/me');if(!me.can_edit)throw new Error('Доступ только для администрации');csrf=me.csrf;await load();}catch(error){document.querySelector('#building-admin-status').textContent=error.message;}})();
