"use strict";
let csrf='',generals=[],editing=null;
const fields=['name','description','image_path','health','attack','defense','initiative','speed','logistics','skills','experience_per_level','max_level','max_attack_bonus','max_defense_bonus','active'];
const numeric=['health','attack','defense','initiative','speed','logistics','experience_per_level','max_level','max_attack_bonus','max_defense_bonus'];
const labels={name:'Название',description:'Описание',image_path:'Изображение',health:'Здоровье',attack:'Базовая атака',defense:'Базовая защита',initiative:'Инициатива',speed:'Скорость',logistics:'Логистика',skills:'Примечание о навыках',experience_per_level:'Опыта на уровень',max_level:'Максимальный уровень',max_attack_bonus:'Предел бонуса атаки',max_defense_bonus:'Предел бонуса защиты',active:'Доступен'};
async function request(path,options={}){const response=await fetch(path,{cache:'no-store',...options});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
function render(){const list=document.querySelector('#general-admin-list');list.replaceChildren(...generals.map(g=>{const card=document.createElement('section'),img=document.createElement('img'),title=document.createElement('h3'),text=document.createElement('p'),edit=document.createElement('button'),del=document.createElement('button');img.src=`/interactive-map/${g.image_path}`;img.alt=g.name;img.className='admin-unit-image';title.textContent=g.name;text.textContent=`атака ${g.attack} · защита ${g.defense} · уровень до ${g.max_level} · ${g.experience_per_level} опыта/уровень${g.active?'':' · отключён'}`;edit.textContent='Редактировать';edit.addEventListener('click',()=>open(g));del.textContent='Удалить';del.className='danger-button';del.addEventListener('click',async()=>{if(!confirm(`Удалить «${g.name}»?`))return;try{await request(`/api/admin/generals/${g.id}`,{method:'DELETE',headers:{'X-CSRF-Token':csrf}});await load();}catch(e){document.querySelector('#general-admin-status').textContent=e.message;}});card.append(img,title,text,edit,del);return card;}));}
function open(g={health:10,attack:1,defense:1,initiative:1,speed:1,logistics:10,experience_per_level:100,max_level:10,max_attack_bonus:5,max_defense_bonus:5,active:true}){editing=g;const form=document.querySelector('#general-editor-form');form.replaceChildren();document.querySelector('#general-editor-title').textContent=g.id?'Редактирование: '+g.name:'Новый генерал';fields.forEach(field=>{const label=document.createElement('label');label.textContent=labels[field];let input;if(field==='active'){input=document.createElement('input');input.type='checkbox';input.checked=g[field];}else if(['description','skills'].includes(field)){input=document.createElement('textarea');input.value=g[field]??'';}else{input=document.createElement('input');input.value=g[field]??'';if(numeric.includes(field)){input.type='number';input.min=0;input.max=10000;}}input.name=field;label.append(input);form.append(label);});const save=document.createElement('button');save.className='save';save.type='submit';save.textContent=g.id?'Сохранить':'Создать';form.append(save);document.querySelector('#general-editor').showModal();}
document.querySelector('#general-editor-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));numeric.forEach(k=>data[k]=Number(data[k]));data.active=e.currentTarget.elements.active.checked;try{await request(editing.id?`/api/admin/generals/${editing.id}`:'/api/admin/generals',{method:editing.id?'PATCH':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});await load();document.querySelector('#general-editor').close();document.querySelector('#general-admin-status').textContent='Сохранено.';}catch(error){document.querySelector('#general-admin-status').textContent=error.message;}});
document.querySelector('#add-general').addEventListener('click',()=>open());document.querySelector('#close-general-editor').addEventListener('click',()=>document.querySelector('#general-editor').close());
async function load(){generals=(await request('/api/admin/generals')).generals;render();}
(async()=>{try{const me=await request('/api/me');if(!me.can_edit)throw new Error('Доступ только для администрации');csrf=me.csrf;await load();document.querySelector('#general-admin-status').textContent=`Генералов: ${generals.length}`;}catch(error){document.querySelector('#general-admin-status').textContent=error.message;}})();
