"use strict";
/**
 * Редактор добываемых и производимых ресурсов.
 * `schemas` задаёт поля формы; код существующего ресурса неизменяем.
 */
let csrf='',catalogues={extractable:[],produced:[]},editing=null;
const schemas={extractable:[['code','Код'],['name','Название'],['typical_locations','Типичные места'],['purpose','Назначение'],['active','Активен']],produced:[['code','Код'],['name','Название'],['ingredients','Ингредиенты'],['required_building','Требуемое строение'],['purpose','Назначение'],['active','Активен']]};
async function request(path,options={}){const response=await fetch(path,{cache:'no-store',...options});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
function renderKind(kind){const list=document.querySelector(`#${kind}-list`);list.replaceChildren(...catalogues[kind].map(resource=>{const card=document.createElement('section'),title=document.createElement('h3'),details=document.createElement('p'),button=document.createElement('button');title.textContent=resource.name;const source=kind==='extractable'?resource.typical_locations:`${resource.ingredients}${resource.required_building?` · строение: ${resource.required_building}`:''}`;details.textContent=`${resource.code} · ${source||'не заполнено'} · ${resource.purpose||'назначение не заполнено'}${resource.active?'':' · отключён'}`;button.textContent='Редактировать';button.addEventListener('click',()=>open(kind,resource));card.append(title,details,button);return card;}));}
function render(){renderKind('extractable');renderKind('produced');}
function open(kind,resource={active:true}){editing={kind,resource};const form=document.querySelector('#resource-editor-form');form.replaceChildren();document.querySelector('#resource-editor-title').textContent=resource.code?`Редактирование: ${resource.name}`:'Новый ресурс';for(const [field,labelText] of schemas[kind]){const label=document.createElement('label');label.textContent=labelText;const input=document.createElement(field==='purpose'||field==='typical_locations'||field==='ingredients'?'textarea':'input');input.name=field;if(field==='active'){input.type='checkbox';input.checked=resource.active;}else{input.value=resource[field]??'';if(field==='code'&&resource.code)input.readOnly=true;}label.append(input);form.append(label);}const save=document.createElement('button');save.type='submit';save.className='save';save.textContent=resource.code?'Сохранить':'Создать';form.append(save);document.querySelector('#resource-editor').showModal();}
document.querySelectorAll('[data-add]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.add)));
document.querySelector('#close-resource-editor').addEventListener('click',()=>document.querySelector('#resource-editor').close());
document.querySelector('#resource-editor-form').addEventListener('submit',async event=>{event.preventDefault();const {kind,resource}=editing,data=Object.fromEntries(new FormData(event.currentTarget));data.active=event.currentTarget.elements.active.checked;const code=data.code;if(resource.code)delete data.code;try{await request(resource.code?`/api/admin/resources/${kind}/${encodeURIComponent(resource.code)}`:`/api/admin/resources/${kind}`,{method:resource.code?'PATCH':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});await load();document.querySelector('#resource-editor').close();document.querySelector('#resource-admin-status').textContent=`Сохранено: ${resource.code||code}`;}catch(error){document.querySelector('#resource-admin-status').textContent=error.message;}});
async function load(){catalogues=await request('/api/admin/resources');render();}
(async()=>{try{const me=await request('/api/me');if(!me.can_edit)throw new Error('Доступ только для администрации');csrf=me.csrf;await load();document.querySelector('#resource-admin-status').textContent=`Добываемых: ${catalogues.extractable.length}; производимых: ${catalogues.produced.length}`;}catch(error){document.querySelector('#resource-admin-status').textContent=error.message;}})();
