"use strict";
let csrf='',units=[],editing=null;
const fields=['name','troop_type','defense','attack','attack_range','speed','description','image_path','price','building','note','active'];
const labels={name:'Название',troop_type:'Тип войск',defense:'Защита',attack:'Атака',attack_range:'Дальность',speed:'Скорость',description:'Описание',image_path:'Изображение',price:'Цена',building:'Строение',note:'Примечание',active:'Доступен для найма'};
async function request(path,options={}){const response=await fetch(path,{cache:'no-store',...options});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
function render(){const list=document.querySelector('#unit-admin-list');list.replaceChildren(...units.map(unit=>{const card=document.createElement('section'),img=document.createElement('img'),title=document.createElement('h3'),text=document.createElement('p'),button=document.createElement('button');img.src=`/interactive-map/${unit.image_path}`;img.alt=unit.name;img.className='admin-unit-image';title.textContent=unit.name;text.textContent=`${unit.troop_type} · атака ${unit.attack} · защита ${unit.defense} · дальность ${unit.attack_range} · скорость ${unit.speed}${unit.active?'':' · отключён'}`;button.textContent='Редактировать';button.addEventListener('click',()=>open(unit));card.append(img,title,text,button);return card;}));}
function open(unit){editing=unit;const form=document.querySelector('#unit-editor-form');form.replaceChildren();document.querySelector('#unit-editor-title').textContent=unit.name;fields.forEach(field=>{const label=document.createElement('label');label.textContent=labels[field];let input;if(field==='active'){input=document.createElement('input');input.type='checkbox';input.checked=unit[field];}else if(['description','note'].includes(field)){input=document.createElement('textarea');input.value=unit[field]??'';}else{input=document.createElement('input');input.value=unit[field]??'';if(['defense','attack','attack_range','speed'].includes(field)){input.type='number';input.min=0;input.max=100;}}input.name=field;label.append(input);form.append(label);});const save=document.createElement('button');save.className='save';save.type='submit';save.textContent='Сохранить';form.append(save);document.querySelector('#unit-editor').showModal();}
document.querySelector('#unit-editor-form').addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));['defense','attack','attack_range','speed'].forEach(key=>data[key]=Number(data[key]));data.active=event.currentTarget.elements.active.checked;try{await request(`/api/admin/units/${editing.id}`,{method:'PATCH',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});await load();document.querySelector('#unit-editor').close();document.querySelector('#unit-admin-status').textContent='Сохранено.';}catch(error){document.querySelector('#unit-admin-status').textContent=error.message;}});
document.querySelector('#close-unit-editor').addEventListener('click',()=>document.querySelector('#unit-editor').close());
async function load(){units=(await request('/api/admin/units')).units;render();}
(async()=>{try{const me=await request('/api/me');if(!me.can_edit)throw new Error('Доступ только для администрации');csrf=me.csrf;await load();document.querySelector('#unit-admin-status').textContent=`Юнитов: ${units.length}`;}catch(error){document.querySelector('#unit-admin-status').textContent=error.message;}})();
