"use strict";
/**
 * Редактор шаблонов боевых единиц и цепочек улучшений.
 * `upgrade_from_unit_id` связывает текущий тип с предыдущим уровнем.
 */
let csrf='',units=[],editing=null;
const fields=['name','troop_type','health','armor','defense','attack','attack_range','speed','initiative','morale','counterattack','description','image_path','price','upgrade_from_unit_id','building','note','active','combat_level'];
const labels={name:'Название',troop_type:'Тип войск',health:'Здоровье',armor:'Броня',defense:'Защита',attack:'Атака',attack_range:'Дальность атаки',speed:'Скорость',initiative:'Инициатива',morale:'Мораль',counterattack:'Контратака',description:'Описание',image_path:'Изображение',price:'Цена ресурсов',upgrade_from_unit_id:'Предыдущий юнит для апгрейда',building:'Требуемое строение (пока не применяется)',note:'Примечание',active:'Доступен для найма',combat_level:'Уровень юнита (1–5)'};
const addButton=document.createElement('button');addButton.id='add-unit';addButton.className='save';addButton.type='button';addButton.textContent='Добавить юнита';document.querySelector('#unit-admin-status').after(addButton);
async function request(path,options={}){const response=await fetch(path,{cache:'no-store',...options});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
function unitPortrait(unit){const figure=document.createElement('div'),img=document.createElement('img'),defense=document.createElement('span'),attack=document.createElement('span');figure.className='unit-portrait admin-unit-image';img.src=`/interactive-map/${unit.image_path}`;img.alt=unit.name;defense.className='unit-image-stat unit-image-defense';defense.textContent=unit.defense;defense.title=`Защита: ${unit.defense}`;attack.className='unit-image-stat unit-image-attack';attack.textContent=unit.attack;attack.title=`Атака: ${unit.attack}`;figure.append(img,defense,attack);return figure;}
function render(){const list=document.querySelector('#unit-admin-list');list.replaceChildren(...units.map(unit=>{const card=document.createElement('section'),title=document.createElement('h3'),text=document.createElement('p'),button=document.createElement('button');title.textContent=unit.name;text.textContent=`${unit.troop_type} · атака ${unit.attack} · защита ${unit.defense} · дальность ${unit.attack_range} · скорость ${unit.speed} · контратака ${unit.counterattack} · уровень ${unit.combat_level}${unit.upgrade_from_name?` · апгрейд из: ${unit.upgrade_from_name}`:''}${unit.building&&!['???',''].includes(unit.building)?` · строение: ${unit.building}`:''}${unit.active?'':' · отключён'}`;button.textContent='Редактировать';button.addEventListener('click',()=>open(unit));card.append(unitPortrait(unit),title,text,button);return card;}));}
function open(unit={health:10,armor:0,initiative:1,morale:100,counterattack:1,active:true,combat_level:1}){editing=unit;const form=document.querySelector('#unit-editor-form');form.replaceChildren();document.querySelector('#unit-editor-title').textContent=unit.id?'Редактирование: '+unit.name:'Новый юнит';fields.forEach(field=>{const label=document.createElement('label');label.textContent=labels[field];let input;if(field==='active'){input=document.createElement('input');input.type='checkbox';input.checked=unit[field];}else if(field==='upgrade_from_unit_id'){input=document.createElement('select');const empty=document.createElement('option');empty.value='';empty.textContent='— обычная покупка —';input.append(empty,...units.filter(candidate=>candidate.id!==unit.id).map(candidate=>{const option=document.createElement('option');option.value=candidate.id;option.textContent=candidate.name;option.selected=candidate.id===unit[field];return option;}));}else if(field==='health'){input=document.createElement('input');input.type='number';input.value=unit[field];input.readOnly=Boolean(unit.id);}else if(['description','note'].includes(field)){input=document.createElement('textarea');input.value=unit[field]??'';}else{input=document.createElement('input');input.value=unit[field]??'';if(['armor','defense','attack','attack_range','speed','initiative','morale','counterattack','combat_level'].includes(field)){input.type='number';input.min=0;input.max=field==='combat_level'?5:100;input.min=field==='combat_level'?1:0;}}input.name=field;label.append(input);form.append(label);});const save=document.createElement('button');save.className='save';save.type='submit';save.textContent=unit.id?'Сохранить':'Создать';form.append(save);document.querySelector('#unit-editor').showModal();}
document.querySelector('#unit-editor-form').addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));['health','armor','defense','attack','attack_range','speed','initiative','morale','counterattack','combat_level'].forEach(key=>data[key]=Number(data[key]));data.upgrade_from_unit_id=data.upgrade_from_unit_id?Number(data.upgrade_from_unit_id):null;data.active=event.currentTarget.elements.active.checked;if(editing.id)delete data.health;try{await request(editing.id?`/api/admin/units/${editing.id}`:'/api/admin/units',{method:editing.id?'PATCH':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});await load();document.querySelector('#unit-editor').close();document.querySelector('#unit-admin-status').textContent='Сохранено.';}catch(error){document.querySelector('#unit-admin-status').textContent=error.message;}});
document.querySelector('#add-unit').addEventListener('click',()=>open());
document.querySelector('#close-unit-editor').addEventListener('click',()=>document.querySelector('#unit-editor').close());
async function load(){units=(await request('/api/admin/units')).units;render();}
(async()=>{try{const me=await request('/api/me');if(!me.can_edit)throw new Error('Доступ только для администрации');csrf=me.csrf;await load();document.querySelector('#unit-admin-status').textContent=`Юнитов: ${units.length}`;}catch(error){document.querySelector('#unit-admin-status').textContent=error.message;}})();
