CREATE TABLE roles (
    role_id integer PRIMARY KEY,
    role_name varchar(50) NOT NULL UNIQUE,
    role_alias varchar(50) NOT NULL UNIQUE
);
CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login varchar(50) NOT NULL,
    user_pass varchar(255) NOT NULL,
    user_email varchar(255) NOT NULL,
    role_id integer NOT NULL REFERENCES roles(role_id)
);
CREATE UNIQUE INDEX users_login_unique ON users(lower(user_login));
CREATE UNIQUE INDEX users_email_unique ON users(lower(user_email));
CREATE TABLE user_sessions (
    token_hash char(64) PRIMARY KEY,
    csrf char(64) NOT NULL,
    user_id integer REFERENCES users(user_id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL
);
CREATE INDEX user_sessions_expiry ON user_sessions(expires_at);
