#!/usr/bin/env python3
"""Generate a standalone hypsometric/bathymetric SVG preview of the hex map."""

from __future__ import annotations

import csv
import html
import math
import re
import urllib.request
from pathlib import Path


MAP_URL = "http://strat.elvizzz.ru/"
ROOT = Path(__file__).resolve().parent
CSV_PATH = ROOT / "hex-initial-parameters.csv"
OUTPUT_PATH = ROOT / "hex-terrain-visualization.svg"
LOCAL_LAND_SOURCES = (
    ROOT / "hex-terrain-final.svg",
    ROOT / "hex-terrain-textured-prototype.svg",
    ROOT / "hex-terrain-visualization.svg",
)
RADIUS = 80
HEX_WIDTH = math.sqrt(3) * RADIUS
CANVAS_WIDTH, CANVAS_HEIGHT = 3200, 2200

# Conventional bathymetric tints: light near shore, progressively darker offshore.
SEA_COLORS = {
    "Мелководье": "#b9e3f3",
    "Шельф": "#73bfe2",
    "Открытое море": "#2878b8",
    "Глубоководье": "#08306b",
}

# Conventional hypsometric tints: green lowlands, ochre uplands, brown mountains.
LAND_COLORS = {
    "Болото": "#79a987",
    "Речная долина": "#84bd72",
    "Луг": "#a8d08d",
    "Равнина": "#b8d68c",
    "Редколесье": "#8fbd77",
    "Густой лес": "#5c9660",
    "Тундра": "#c8c7a5",
    "Полупустыня": "#dbc58b",
    "Холмы": "#c49a62",
    "Горы": "#9b6a43",
    "Высокогорье": "#68452f",
}


def land_paths_from_clip(source: str) -> list[str]:
    """Read contours from a map generated by this project."""
    clip = re.search(
        r'<clipPath\s+id="land-clip"[^>]*>(.*?)</clipPath>',
        source,
        flags=re.DOTALL,
    )
    if not clip:
        return []
    return re.findall(r'<path\s+[^>]*d="([^"]+)"', clip.group(1))


def fetch_land_paths() -> list[str]:
    # Prefer the checked-in contours. Regeneration must keep working if the
    # public site's HTML or SVG structure changes or the site is unavailable.
    for path in LOCAL_LAND_SOURCES:
        if path.exists():
            paths = land_paths_from_clip(path.read_text(encoding="utf-8"))
            if paths:
                print(f"Using local land contours from {path}")
                return paths

    request = urllib.request.Request(MAP_URL, headers={"User-Agent": "Strat.elvizzz-svg-preview/0.1"})
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            source = response.read().decode("utf-8")
    except (OSError, UnicodeError) as error:
        raise RuntimeError("Land contours are unavailable locally and could not be downloaded") from error

    paths = re.findall(r'<path\s+[^>]*d="([^"]+)"[^>]*fill="#D9D9D9"', source)
    if not paths:
        raise RuntimeError("Land contours were not found locally or in the source site")
    return paths


def polygon_points(q: int, r: int) -> str:
    cx = HEX_WIDTH * (q + r / 2)
    cy = RADIUS * 1.5 * r
    points = []
    for index in range(6):
        angle = math.radians(60 * index - 30)
        points.append(f"{cx + RADIUS * math.cos(angle):.2f},{cy + RADIUS * math.sin(angle):.2f}")
    return " ".join(points)


def land_type(value: str) -> str:
    # Coastal values use the form "coast / inland terrain".
    return value.rsplit(" / ", 1)[-1]


def write_svg(rows: list[dict[str, str]], land_paths: list[str]) -> None:
    out: list[str] = []
    out.append('<?xml version="1.0" encoding="UTF-8"?>')
    out.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1100" '
        f'viewBox="0 0 {CANVAS_WIDTH} {CANVAS_HEIGHT}" role="img" '
        f'aria-labelledby="map-title map-description">'
    )
    out.append('<title id="map-title">Гипсометрическая карта гексов Strat.elvizzz</title>')
    out.append('<desc id="map-description">Стартовая визуализация высот суши и глубин моря по таблице параметров гексов.</desc>')
    out.append('<defs>')
    out.append('<clipPath id="land-clip">')
    for path in land_paths:
        out.append(f'<path d="{html.escape(path, quote=True)}"/>')
    out.append('</clipPath>')
    out.append('<filter id="legend-shadow" x="-20%" y="-20%" width="140%" height="140%">')
    out.append('<feDropShadow dx="0" dy="5" stdDeviation="8" flood-opacity="0.35"/>')
    out.append('</filter>')
    out.append('</defs>')
    out.append('<rect width="3200" height="2200" fill="#08306b"/>')
    out.append('<g id="hex-terrain">')

    for row in rows:
        category = row["Категория"]
        if category == "Вне полотна":
            continue
        q, r = int(row["Q"]), int(row["R"])
        points = polygon_points(q, r)
        terrain = row["Тип местности"]
        title = html.escape(
            f"Q={q}, R={r}; {category}; {terrain}; ресурс: {row['Основной ресурс']}", quote=False
        )
        if category == "Море":
            fill = SEA_COLORS.get(terrain, "#2878b8")
            out.append(f'<polygon points="{points}" fill="{fill}"><title>{title}</title></polygon>')
        elif category == "Суша":
            fill = LAND_COLORS.get(land_type(terrain), "#b8d68c")
            out.append(f'<polygon points="{points}" fill="{fill}"><title>{title}</title></polygon>')
        else:
            sea_fill = SEA_COLORS.get("Мелководье", "#b9e3f3")
            land_fill = LAND_COLORS.get(land_type(terrain), "#b8d68c")
            out.append(f'<g><title>{title}</title><polygon points="{points}" fill="{sea_fill}"/>')
            out.append(f'<polygon points="{points}" fill="{land_fill}" clip-path="url(#land-clip)"/></g>')

    out.append('</g>')
    out.append('<g id="hex-grid" fill="none" stroke="#203040" stroke-opacity="0.48" stroke-width="2">')
    for row in rows:
        if row["Категория"] != "Вне полотна":
            out.append(f'<polygon points="{polygon_points(int(row["Q"]), int(row["R"]))}"/>')
    out.append('</g>')

    # Compact map legend placed over the unoccupied sea area in the lower-left corner.
    out.append('<g id="legend" transform="translate(55 1460)" font-family="Segoe UI, Arial, sans-serif" filter="url(#legend-shadow)">')
    out.append('<rect width="620" height="650" rx="24" fill="#ffffff" fill-opacity="0.93" stroke="#334155" stroke-width="3"/>')
    out.append('<text x="34" y="55" font-size="34" font-weight="700" fill="#172033">Высоты и глубины</text>')
    out.append('<text x="34" y="90" font-size="21" fill="#475569">Предварительная визуализация</text>')
    legend_items = [
        ("Мелководье", SEA_COLORS["Мелководье"]),
        ("Шельф", SEA_COLORS["Шельф"]),
        ("Открытое море", SEA_COLORS["Открытое море"]),
        ("Глубоководье", SEA_COLORS["Глубоководье"]),
        ("Низменности и луга", LAND_COLORS["Луг"]),
        ("Леса", LAND_COLORS["Густой лес"]),
        ("Сухие равнины", LAND_COLORS["Полупустыня"]),
        ("Холмы", LAND_COLORS["Холмы"]),
        ("Горы", LAND_COLORS["Горы"]),
        ("Высокогорье", LAND_COLORS["Высокогорье"]),
    ]
    for index, (label, color) in enumerate(legend_items):
        y = 125 + index * 48
        out.append(f'<rect x="35" y="{y}" width="62" height="32" rx="4" fill="{color}" stroke="#334155"/>')
        out.append(f'<text x="116" y="{y + 25}" font-size="23" fill="#172033">{label}</text>')
    out.append('<line x1="35" y1="615" x2="585" y2="615" stroke="#94a3b8"/>')
    out.append('<text x="35" y="640" font-size="17" fill="#475569">Источник: strat.elvizzz.ru · версия 0.1</text>')
    out.append('</g>')
    out.append('</svg>')
    OUTPUT_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")


def main() -> None:
    if not CSV_PATH.exists():
        raise RuntimeError(f"Generate the parameter table first: {CSV_PATH}")
    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as stream:
        rows = list(csv.DictReader(stream, delimiter=";"))
    land_paths = fetch_land_paths()
    write_svg(rows, land_paths)
    print(f"Generated {OUTPUT_PATH} from {len(rows)} coordinate rows and {len(land_paths)} land contours")


if __name__ == "__main__":
    main()
