"""Synchronize the seed catalogue with the reviewed V6 raster scan."""
import csv
import json
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'data/import/hex-initial-parameters.csv'
SHARES = ROOT / 'data/import/hex-v6-land-shares.csv'
OBJECT_FIELDS = ('Уровень гекса','Постройка','Дорога','Водная переправа','Объекты гекса')
DIRECTIONS = ((1,0),(-1,0),(0,1),(0,-1),(1,-1),(-1,1))
SEA_RESOURCES = {'Нет','Рыба','Моллюски','Водоросли','Киты','Жемчуг'}

with SHARES.open(encoding='utf-8-sig', newline='') as stream:
    shares={(int(row['Q']),int(row['R'])):int(row['Доля суши, %'])
            for row in csv.DictReader(stream,delimiter=';')}
with SOURCE.open(encoding='utf-8-sig', newline='') as stream:
    rows=list(csv.DictReader(stream,delimiter=';'))
fieldnames=list(rows[0])+[name for name in OBJECT_FIELDS if name not in rows[0]]
by_coord={(int(row['Q']),int(row['R'])):row for row in rows}
for q,r in shares:
    by_coord.setdefault((q,r),{name:'' for name in fieldnames}|{
        'ID':f'Q{q:+03d}-R{r:+03d}','Q':str(q),'R':str(r)})

categories={coord:('Море' if share<=5 else 'Суша' if share>=95 else 'Побережье')
            for coord,share in shares.items()}
distance={coord:0 for coord,category in categories.items() if category!='Море'}
pending=deque(distance)
while pending:
    q,r=pending.popleft()
    for dq,dr in DIRECTIONS:
        other=(q+dq,r+dr)
        if other in shares and other not in distance:
            distance[other]=distance[(q,r)]+1; pending.append(other)

def base_land(terrain):
    result=(terrain or 'Редколесье').split('/')[-1].strip()
    return result if result not in ('Мелководье','Шельф','Открытое море','Глубоководье') else 'Редколесье'

for coord,share in shares.items():
    row=by_coord[coord]; old=row.get('Категория',''); category=categories[coord]
    for name in OBJECT_FIELDS: row.setdefault(name,'')
    row['Доля суши, %']=str(share); row['Категория']=category
    if category=='Море':
        dist=distance.get(coord,4)
        terrain='Мелководье' if dist<=1 else 'Шельф' if dist==2 else 'Открытое море' if dist<=4 else 'Глубоководье'
        depth={'Мелководье':'1','Шельф':'2','Открытое море':'3','Глубоководье':'4'}[terrain]
        resource=row.get('Основной ресурс') if row.get('Основной ресурс') in SEA_RESOURCES else 'Нет'
        row.update({'Тип местности':terrain,'Проходимость':'2' if terrain=='Мелководье' else '1',
                    'Защита':'0','Плодородие':'','Пресная вода':'','Глубина':depth,
                    'Опасность':str(min(5,1+int(depth))),'Дополнительный объект':'',
                    'Основной ресурс':resource,
                    'Богатство ресурса':row.get('Богатство ресурса','0') if resource!='Нет' else '0'})
    elif category=='Побережье':
        land=base_land(row.get('Тип местности'))
        prefix='Дельта реки' if row.get('Дополнительный объект')=='Река' else 'Островной берег' if old=='Море' else 'Побережье'
        row['Тип местности']=f'{prefix} / {land}'
        row['Глубина']='1'; row.setdefault('Течение','3')
        if old=='Море':
            row.update({'Проходимость':'2','Защита':'1','Плодородие':'3','Пресная вода':'1','Опасность':'2'})
    else:
        row['Тип местности']=base_land(row.get('Тип местности'))
        row['Глубина']=''; row['Течение']=''
    if old!=category:
        row['Комментарий']=f'Категория уточнена по актуальной подложке V6: {old or "нет данных"} → {category}'

rows=sorted(by_coord.values(),key=lambda row:(int(row['R']),int(row['Q'])))
with SOURCE.open('w',encoding='utf-8-sig',newline='') as stream:
    writer=csv.DictWriter(stream,fieldnames=fieldnames,delimiter=';',quoting=csv.QUOTE_ALL)
    writer.writeheader();writer.writerows(rows)
print(f'V6 raster cells synchronized: {len(shares)}; catalogue rows: {len(rows)}')

# Existing databases are not re-imported from CSV. Generate a reviewed upsert
# migration that changes descriptive metadata but never ownership or baronies.
migration=ROOT/'data/migrations/016_v6_hex_metadata.sql'
excluded={'ID','Название','Название территории','Пресная вода','Тип владельца','Владелец',
          'ID территории','Название баронии','Цвет баронии','Герб баронии'}
values=[]
for coord in sorted(shares,key=lambda item:(item[1],item[0])):
    row=by_coord[coord]
    patch={key:value for key,value in row.items() if key not in excluded and value!=''}
    patch.update({'Q':str(coord[0]),'R':str(coord[1]),'Статус данных':'Описание заполнено'})
    encoded=json.dumps(patch,ensure_ascii=False,separators=(',',':')).replace("'","''")
    values.append(f"({coord[0]},{coord[1]},'{encoded}'::jsonb)")
descriptive=[key for key in fieldnames if key not in excluded and key not in ('Q','R')]
delete_keys=','.join("'"+key.replace("'","''")+"'" for key in descriptive+['Статус данных'])
migration.write_text(
    "-- Generated by scripts/update-v6-hex-catalogue.py; ownership fields are intentionally excluded.\n"
    "INSERT INTO hexes(q,r,data) VALUES\n  "+",\n  ".join(values)+
    f"\nON CONFLICT(q,r) DO UPDATE SET data=(hexes.data - ARRAY[{delete_keys}]) || excluded.data, updated_at=now();\n",
    encoding='utf-8',newline='\n')
print(f'Generated existing-database migration: {migration.name}')
