/var/log/fail2ban.log {
    daily
    rotate 14
    maxsize 5M
    missingok
    notifempty
    compress
    delaycompress
    create 0640 root adm
    postrotate
        /usr/bin/fail2ban-client flushlogs >/dev/null 2>&1 || true
    endscript
}
